[book]
authors = ["HackTricks Team"]
language = "en"
src = "src"
title = "HackTricks"

[build]
create-missing = false
extra-watch-dirs = ["translations"]

[preprocessor.tabs]

[preprocessor.hacktricks]
command = "python3 ./hacktricks-preprocessor.py"
env = "prod"

[output.html]
additional-css = ["theme/tabs.css"]
additional-js = [
    "theme/tabs.js",
    "theme/ht_searcher.js",
    "theme/sponsor.js",
    "theme/ai.js"
]
no-section-label = true
preferred-dark-theme = "hacktricks-dark"
default-theme = "hacktricks-light"

[output.html.fold]
enable = true # whether or not to enable section folding
level = 0     # the depth to start folding


[output.html.print]
enable = false # whether or not to enable print
